version: "3"
services:
  bitcoin-core:
    container_name: mainnet-bitcoin-core
    image: ruimarinho/bitcoin-core:0.21.1
    command: -printtoconsole -txindex -server -rpcuser=user -rpcpassword=password -rpcallowip=0.0.0.0/0 -rpcbind=0.0.0.0
    environment:
      - BITCOIN_DATA=/data/bitcoin
      - ION_DATA_VOLUME=db_data
    volumes:
      # the ":-" means if ION_DATA_VOLUME is not set or empty, substitute with "~/ion-data"
      # see https://docs.docker.com/compose/compose-file/compose-file-v3/#variable-substitution for detail on variable substitution
      - ${ION_DATA_VOLUME:-~/ion-data}/bitcoin:/data/bitcoin
    ports:
      - "8332:8332"
    logging:
      driver: awslogs
      options:
         awslogs-group: ion-bitcoin-core
         awslogs-region: us-west-2
         awslogs-stream-prefix: ion

  mongo:
    container_name: mongo
    image: mongo:4.0.27-xenial
    environment:
      - ION_DATA_VOLUME=db_data
    volumes:
      # mongo image by default writes to `/data/db` inside the container
      - ${ION_DATA_VOLUME:-~/ion-data}/mongo:/data/db
    ports:
      - "27017:27017"
    logging:
      driver: awslogs
      options:
         awslogs-group: ion-mongo
         awslogs-region: us-west-2
         awslogs-stream-prefix: ion

  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:v0.13.0
    environment:
      - IPFS_PATH=/data/ipfs
      - ION_DATA_VOLUME=db_data
    volumes:
      - ${ION_DATA_VOLUME:-~/ion-data}/ipfs:/data/ipfs
    ports:
      - "4001:4001" # inbound TCP traffic
      - "5001:5001" # API port
    logging:
        driver: awslogs
        options:
           awslogs-group: ion-ipfs
           awslogs-region: us-west-2
           awslogs-stream-prefix: ion

  ion-bitcoin:
    container_name: mainnet-ion-bitcoin
    image: thehenrytsai/ion:1.0.4
    command: [ node, "src/bitcoin.js" ]
    working_dir: /ion
    environment:
      - ION_DATA_VOLUME=db_data
      - ION_BITCOIN_CONFIG_FILE_PATH=/config/docker-mainnet-bitcoin-config.json
      - ION_BITCOIN_VERSIONING_CONFIG_FILE_PATH=/config/mainnet-bitcoin-versioning.json
    volumes:
      # for optional fast initialization feature
      - ${ION_DATA_VOLUME:-~/ion-data}/bitcoin:/data/bitcoin
    ports:
      - "3002:3002"
    logging:
        driver: awslogs
        options:
           awslogs-group: ion-bitcoin
           awslogs-region: us-west-2
           awslogs-stream-prefix: ion

  ion-core:
    container_name: mainnet-ion-core
    image: thehenrytsai/ion:1.0.4
    command: [ node, "src/core.js" ]
    working_dir: /ion
    environment:
      - ION_DATA_VOLUME=db_data
      - ION_CORE_CONFIG_FILE_PATH=/config/docker-mainnet-core-config.json
      - ION_CORE_VERSIONING_CONFIG_FILE_PATH=/config/mainnet-core-versioning.json
    ports:
      - "3000:3000"
    logging:
      driver: awslogs
      options:
         awslogs-group: ion-core
         awslogs-region: us-west-2
         awslogs-stream-prefix: ion
